services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql
  # redis:
  #   image: redis:7
  #   environment:
  #     REDIS_HOST: ${REDIS_HOST}
  #     REDIS_PORT: ${REDIS_PORT}
  #   container_name: rediska
  #   restart: always
  #   ports:
  #     - "${REDIS_PORT}:6379"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: url-shorter
#    volumes:
#      - ./:/app
#    working_dir: /app
#    depends_on:
#      - db
#    env_file:
#      - .env
#    ports:
#      - "8000:8000"
#    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data: